<a href="https://colab.research.google.com/github/farah1432/DO180-apps/blob/master/00_PytorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


Introduction to Tensor

In [3]:
import torch
#scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()


7

In [6]:
#Vector
vector = torch.tensor([7,7])
print(vector)

tensor([7, 7])


In [7]:
vector.shape

torch.Size([2])

In [8]:
vector.ndim

1

In [9]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Tensor
Tensor = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
print(Tensor)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


In [12]:
Tensor.shape

torch.Size([1, 3, 3])

Create a random tensor of size (3,4)

In [13]:
random_tensor = torch.rand(10,4)
random_tensor

tensor([[0.4992, 0.8815, 0.1138, 0.9452],
        [0.0684, 0.6878, 0.9181, 0.2078],
        [0.2537, 0.3211, 0.8659, 0.2507],
        [0.5387, 0.6053, 0.2061, 0.7447],
        [0.4052, 0.3205, 0.7563, 0.4673],
        [0.4672, 0.5965, 0.5409, 0.2355],
        [0.3613, 0.2030, 0.6208, 0.3091],
        [0.1513, 0.2466, 0.3878, 0.2601],
        [0.7429, 0.4702, 0.1816, 0.7545],
        [0.1444, 0.3460, 0.1058, 0.6569]])

In [14]:
random_tensor.ndim

2

In [15]:
random_image_size_tensor = torch.rand(size=(224, 224, 4))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 4]), 3)

### Zeros and Ones

In [16]:
# Create a tensor of all zeros
zeros = torch.zeros(size=( 2,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

In [19]:
random_tensor.dtype

torch.float32

## Creating a range of tensors

In [20]:
# Use torch.arange()
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
torch.__version__

'2.10.0+cpu'

In [22]:
one_to_ten = torch.arange(start=1, end=10, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [23]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

## Tensor Datatypes
Note: 3 major issues that cause error in Tensor.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 4.0, 7.0], dtype=torch.float32, device=None, requires_grad=False)
float_32_tensor

tensor([3., 4., 7.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 7.], dtype=torch.float16)

In [27]:
float_32_tensor * float_16_tensor

tensor([ 9., 16., 49.])

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [29]:
int_32_tensor * float_16_tensor

tensor([ 9., 24., 63.], dtype=torch.float16)

### Getting information from tensors ( Tensor attributes)
Tensors not right datatype - use tensor.dtype
Tensors not right shape - use tensor.shape
Tensors not on the right device - use tensor.device


In [30]:
# Create a tensor
some_tensor = torch.rand (3, 4)
some_tensor

tensor([[0.5693, 0.5333, 0.1792, 0.3606],
        [0.8791, 0.5256, 0.4581, 0.7487],
        [0.9164, 0.1408, 0.6718, 0.5855]])

In [31]:
some_tensor.size()
torch.Size([3,4])

torch.Size([3, 4])

In [32]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")
print

tensor([[0.5693, 0.5333, 0.1792, 0.3606],
        [0.8791, 0.5256, 0.4581, 0.7487],
        [0.9164, 0.1408, 0.6718, 0.5855]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

### Manipulating Tensors ( tensor operations)
Tensor operations include:
Addition
Subtraction
Multiplication (element-wise)
Division
Matrix multiplication


In [33]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [34]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Multiply method 2
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [37]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

## Matrix multiplication
Two ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product) most common
Most information on multiplying matrixs - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that need to satisfy for matrix multiplication.

1. The ** inner dimensions ** must match:

(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the ** outer dimension **

(2, 3) @ (3, 2) shape (3, 2)


In [38]:
# Element wise multiplication
print(tensor, "*" , tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [39]:
# Matrix multiplication
torch.matmul(tensor,tensor  )

tensor(14)

In [40]:
value = 0
for i in range(len(tensor)) :
  value += tensor[i] * tensor [i]
print(value)

tensor(14)


### Alternative For Loop

This loop iterates directly over the elements of the tensor.

In [41]:
value_for_loop_2 = 0
for element in tensor:
  value_for_loop_2 += element * element
print(value_for_loop_2)

tensor(14)


One of the most common errors in deep learning: shape errors

Tensor Min, Max, Mean, Median

In [42]:
# Create a tensor
x = torch.arange( 0, 80, 5)
x, x.dtype

(tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75]),
 torch.int64)

In [43]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [44]:
# Find the max
torch.max(x), x.max()

(tensor(75), tensor(75))

In [45]:
# Find the mean [torch.mean() function need float.32 )

In [46]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(37.5000), tensor(37.5000))

In [47]:
# Find the sum
torch.sum(x), x.sum()

(tensor(600), tensor(600))

# Find positional min and max

In [48]:
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [49]:
x.argmin()

tensor(0)

In [50]:
x[7]

tensor(35)

In [51]:
x.argmax()

tensor(15)

In [52]:
x[15]

tensor(75)

## Reshaping, stacking, squeezing and unsqueezing
Reshaping - Reshapes an input tensor to a defined ShapeType
View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
Stacking - combine multiple tensors on top of each other (vstack or hstack)
Squeeze - removes all '1' dimensions from a tensor
Unsqueeze - add a '1' dimension to a target tensor
Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [53]:
## Create a tensor
import torch
x = torch.arange (1., 10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
# Add an extra dimension (dimension must be multiply/compatible with the size)

X_reshaped = x.reshape(1, 9)
X_reshaped, X_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
X_reshaped = x.reshape(9, 1)
X_reshaped, X_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [56]:
# Change the view
z=x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
# Changing z changes x (because the view of a tensor shares the same memory as the original)
z[ :, 7] =9
z,x

(tensor([[1., 2., 3., 4., 5., 6., 7., 9., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 9., 9.]))

In [58]:
# Stack tensors on top each other
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 9., 9.],
        [1., 2., 3., 4., 5., 6., 7., 9., 9.],
        [1., 2., 3., 4., 5., 6., 7., 9., 9.]])

In [59]:
# torch.squeeze() - removes extra dimension from x_reshaped
print(f"Previous tensor: {X_reshaped}")
print(f"Previous shape: {X_reshaped.shape}")
# Remove extra dimensions from x_reshaped
x_squeezed = X_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [9.],
        [9.]])
Previous shape: torch.Size([9, 1])
New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 9., 9.])
New shape: torch.Size([9])


In [60]:
# torch.unsqueeze () - adds a single dimension to a target tensor at a specific dimension.
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze (dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 9., 9.])
Previous shape: torch.Size([9])
New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 9., 9.]])
New shape: torch.Size([1, 9])


In [61]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # Hieght, width, color channel
# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

# premute and original share the same space both are view


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [66]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

indexing with PyTorch is similar to indexing in NumPy

In [74]:
# Create a tensor
import torch
x = torch.arange(1, 13 ). reshape(1, 3, 4)
x, x.shape


(tensor([[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]]]),
 torch.Size([1, 3, 4]))

In [75]:
# Let's index on our new tensor
x[0]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [77]:
# Let's index the new tensor part by part
x[0]

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [78]:
# Now Index in the mioddle bracket (dim=1)
x[0][0]

tensor([1, 2, 3, 4])

In [79]:
# Index on the most inner bracket (last dimension)
x[0][1][1]

tensor(6)

In [84]:
# Index on x to return 9
x [0][2][0]

tensor(9)

In [87]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd
x[:, 1, 1]


tensor([6])

In [95]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension

x [ 0, 0, :]

tensor([1, 2, 3, 4])

In [96]:
x

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [98]:
x [:, :, 3]

tensor([[ 4,  8, 12]])

## PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor ->torch.from_munpy(ndarray)
* PyTorch tensor->NumpPy-> torch.tensor.numpy()

In [100]:
## NumPy array in tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## NumPy default datatype is float64

In [108]:

array.dtype

dtype('float64')

In [106]:
tensor.dtype

torch.float64

## torch default datatype is float32

In [109]:

torch.arange(1.0, 8.0).dtype


torch.float32

In [110]:
## Change the value of NumPy what will this do to 'tensor'
array = array + 1
array, tensor
# tensor value don't change

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [112]:
# Tensor to NumPy array
tensor = torch.ones(4)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor


(tensor([1., 1., 1., 1.]), array([1., 1., 1., 1.], dtype=float32))

In [113]:
## Change the tensor what happens to 'NumPy tensor'
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2.]), array([1., 1., 1., 1.], dtype=float32))

## Reproducibility(trying to take random out of random)
In short how a nueral network learns:
start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a **Random seed**

Essentially what the random seed does is "flavour" the randomness.

https://docs.pytorch.org/docs/stable/notes/randomness.html

In [118]:
 ## Create two random tensors
 random_tensor_A = torch.rand(3, 4)
 random_tensor_B = torch.rand(3, 4)

 print(random_tensor_A)
 print(random_tensor_B)
 print(random_tensor_A == random_tensor_B)


tensor([[6.1064e-01, 1.6503e-01, 5.0664e-06, 4.3811e-01],
        [9.4235e-01, 9.5054e-01, 4.8411e-01, 2.8684e-01],
        [3.1836e-01, 1.2266e-01, 3.5119e-01, 8.4853e-01]])
tensor([[0.8948, 0.1090, 0.4107, 0.6627],
        [0.2202, 0.5643, 0.1574, 0.1274],
        [0.9138, 0.3726, 0.0456, 0.7321]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [121]:
## Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED) ## this code only work for 1 line
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print (random_tensor_C)
print (random_tensor_D)
print (random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [114]:
torch.rand(4, 4)

tensor([[0.6023, 0.4354, 0.5676, 0.1141],
        [0.5127, 0.0162, 0.2901, 0.8072],
        [0.8534, 0.1345, 0.2828, 0.9390],
        [0.8994, 0.7162, 0.9608, 0.1030]])

GPU and CPU

In [122]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [102]:
## Check for GPU access with PyTorch # Best practice set the device agnoistic.
import torch
torch.cuda.is_available()

False

In [104]:
## Setup device agnoistic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [123]:
# Count number of devices
torch.cuda.device_count()

0

In [124]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [126]:
 # Move tensor on GPU (if available)
 tensor_on_GPU = tensor.to(device)
 tensor_on_GPU

tensor([1, 2, 3])