<a href="https://colab.research.google.com/github/farah1432/DO180-apps/blob/master/AI_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:

import torch
import torch.nn as nn
import numpy as np

x = np.array([
    [0.0, 0.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [1.0, 1.0]

])
x = torch.tensor(x)
print(type (x))

<class 'torch.Tensor'>


In [97]:
X = torch.Tensor (
    [
    [0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0],
    [1.0, 0.0, 0.0],
    [1.0, 1.0, 1.0]
    ]

)

Y = torch.Tensor(
    [
        [0.0],
        [0.0],
        [0.0],
        [1.0]
    ]
)

In [98]:
print (np.random.rand(5))

[0.23114566 0.24542433 0.48467226 0.18007148 0.11746061]


In [99]:
print (torch.rand(5))

tensor([0.9408, 0.1332, 0.9346, 0.5936, 0.8694])


In [100]:

t = torch.rand (5)
t = t.sum (axis=0)
print(t)

tensor(3.1976)


In [101]:
#X0=1, x1, x2, x3

#w0, w1, w2, w3

class Perceptron(nn.Module):
    def __init__(self, input_size):
        super( Perceptron, self).__init__()
        self.input_size = input_size
        self.weight = nn.Parameter(
           torch.randn(input_size)
        )
        self.bias= nn.Parameter(
           torch.zeros(1)
        )

    def forward(self, x):
      z = x @ self.weight + self.bias
      y_pred = torch.sigmoid(z)
      return y_pred

In [102]:
model = Perceptron(input_size=3)


In [103]:
torch.manual_seed(42)
x = torch.randn(3)
print(x)

y_pred = model(x)
print(y_pred)

tensor([0.3367, 0.1288, 0.2345])
tensor([0.5572], grad_fn=<SigmoidBackward0>)


In [104]:
print(*model.parameters())

Parameter containing:
tensor([0.2303, 0.3930, 0.4327], requires_grad=True) Parameter containing:
tensor([0.], requires_grad=True)


In [105]:
# """ Cost function """

criterion = nn.BCELoss()

# Optimizers
optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.0001
)


In [106]:
y_pred = model(X)
print(y_pred)

tensor([0.5000, 0.5970, 0.5573, 0.7419], grad_fn=<SigmoidBackward0>)


In [108]:
y_pred.ndim

1

In [109]:
y_pred.shape

torch.Size([4])

In [112]:
y_pred = y_pred.unsqueeze(1)
print(y_pred)

tensor([[[[0.5000]]],


        [[[0.5970]]],


        [[[0.5573]]],


        [[[0.7419]]]], grad_fn=<UnsqueezeBackward0>)


In [113]:
print(y_pred.shape)

torch.Size([4, 1, 1, 1])
